version: "3.3"
services:
  web:
    image: ms-web
    depends_on:
      - database
    ports:
      - "8000:80"
    configs:
      - source: web-app.conf
        target: /etc/nginx/nginx.conf
  
  admin:
    image: ms-admin
    depends_on:
      - database
    ports:
      - "8001:80"
    configs:
      - source: web-app.conf
        target: /etc/nginx/nginx.conf
  
  database:
    image: mariadb:10.3.10
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
      MYSQL_DATABASE: music_shop_db
      MYSQL_USER: music_shop
      MYSQL_PASSWORD_FILE: /run/secrets/user_password
    ports:
      - "3306:3306"
    secrets:
      - root_password
      - user_password
    volumes:
      - ./configs/sql/db_creation.sql:/docker-entrypoint-initdb.d/db_creation.sql
      - database_volume:/var/lib/mysql
  
  api:
    image: ms-api
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/build/libs/music-shop-server-0.1.0.jar"]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

configs:
  web-app.conf:
    external: true
secrets:
  root_password:
    external: true
  user_password:
    external: true
volumes:
  database_volume:
    external: true
